CREATE SCHEMA IF NOT EXISTS PRUEBA;
CREATE TABLE IF NOT EXISTS PRUEBA.USUARIO (ID BIGINT NOT NULL,FULL_NAME VARCHAR(50),USER_NAME VARCHAR(10),PRIMARY KEY (ID));
CREATE TABLE PRUEBA.RECETA (ID INTEGER NOT NULL,NOMBRE VARCHAR(25),DESCRIPCION VARCHAR(250),FECHA DATE,PRIMARY KEY (ID));
