CREATE SCHEMA IF NOT EXISTS PRUEBA;
CREATE TABLE IF NOT EXISTS PRUEBA.REDONDOS (ID INTEGER NOT NULL,NOMBRE VARCHAR(25),DESCRIPCION VARCHAR(250),FECHA DATE,PRIMARY KEY (ID));
CREATE TABLE PRUEBA.RECETA (ID INTEGER NOT NULL,NOMBRE VARCHAR(25),DESCRIPCION VARCHAR(250),FECHA DATE,PRIMARY KEY (ID));
